=== Fcmam5/algeria-api/data/WilayaList.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Wilaya list",
  "type": "array",
  "maxLength": 48,
  "minLength": 48,
  "items": {
    "type": "object",
    "properties": {
      "mattricule": {
        "description": "The province (Wilaya) code",
        "type": "number",
        "minimum": 1,
        "maximum": 48
      },
      "name": {
        "type": "string",
        "minLength": 3
      },
      "name_en": {
        "type": "string",
        "minLength": 3
      },
      "name_ar": {
        "type": "string",
        "pattern": "^[\u0621-\u064A\\s]+$"
      },
      "phoneCodes": {
        "type": "array",
        "items": {
          "type": "number"
        }
      },
      "adjacentWilayas": {
        "type": "array",
        "items": {
          "type": "number"
        }
      },
      "postalCodes": {
        "type": "array",
        "items": {
          "type": "number"
        }
      },
      "dairats": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "code": {
              "type": "number"
            },
            "name": {
              "type": "string",
              "minLength": 3
            },
            "name_ar": {
              "type": "string",
              "pattern": "^[\u0621-\u064A\\s\\(\\)]+$"
            },
            "name_en": {
              "type": "string",
              "minLength": 3
            },
            "baladyiats": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "code": {
                    "type": "number"
                  },
                  "name": {
                    "type": "string",
                    "minLength": 3
                  },
                  "name_ar": {
                    "type": "string",
                    "pattern": "^[\u0621-\u064A\\s\\(\\)]+$"
                  },
                  "name_en": {
                    "type": "string",
                    "minLength": 3
                  }
                },
                "additionalProperties": false,
                "required": [
                  "code",
                  "name",
                  "name_en",
                  "name_ar"
                ]
              }
            }
          },
          "additionalProperties": false,
          "required": [
            "code",
            "name",
            "name_en",
            "name_ar"
          ]
        }
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "mattricule",
    "name",
    "name_en",
    "name_ar",
    "phoneCodes",
    "adjacentWilayas",
    "dairats",
    "postalCodes"
  ]
}

=== Fcmam5/algeria-api/data/WilayaList.min.json
[{"mattricule":1,"name":"Adrar","name_ar":"أدرار","name_en":"Adrar","phoneCodes":[49],"postalCodes":[1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074],"dairats":[{"code":101,"name":"ADRAR","name_ar":"أدرار","name_en":"ADRAR","baladyiats":[{"code":101,"name":"ADRAR","name_en":"ADRAR","name_ar":"أدرار"},{"code":121,"name":"OULED AHMED TIMMI","name_en":"OULED AHMED TIMMI","name_ar":"أولاد أحمد تيمي"},{"code":122,"name":"BOUDA","name_en":"BOUDA","name_ar":"بودة"}]},{"code":103,"name":"CHAROUINE","name_ar":"شروين","name_en":"CHAROUINE","baladyiats":[{"code":103,"name":"CHAROUINE","name_en":"CHAROUINE","name_ar":"شروين"},{"code":124,"name":"TALMINE","name_en":"TALMINE","name_ar":"طالمين"},{"code":127,"name":"OULED AISSA","name_en":"OULED AISSA","name_ar":"أولاد عيسى"}]},{"code":104,"name":"REGGANE","name_ar":"رقان","name_en":"REGGANE","baladyiats":[{"code":104,"name":"REGGANE","name_en":"REGGANE","name_ar":"رقان"},{"code":118,"name":"SALI","name_en":"SALI","name_ar":"سالي"}]},{"code":108,"name":"TSABIT","name_ar":"تسابيت","name_en":"TSABIT","baladyiats":[{"code":108,"name":"TSABIT","name_en":"TSABIT","name_ar":"تسابيت"},{"code":126,"name":"SEBAA","name_en":"SEBAA","name_ar":"السبع"}]},{"code":109,"name":"TIMIMOUN","name_ar":"تيميمون","name_en":"TIMIMOUN","baladyiats":[{"code":109,"name":"TIMIMOUN","name_en":"TIMIMOUN","name_ar":"تيميمون"},{"code":110,"name":"OULED SAID","name_en":"OULED SAID","name_ar":"أولاد السعيد"}]},{"code":111,"name":"ZAOUIAT KOUNTA","name_ar":"زاوية كنتة","name_en":"ZAOUIAT KOUNTA","baladyiats":[{"code":105,"name":"IN ZGHMIR","name_en":"IN ZGHMIR","name_ar":"إن زغمير"},{"code":111,"name":"ZAOUIET KOUNTA","name_en":"ZAOUIET KOUNTA","name_ar":"زاوية كنتة"}]},{"code":112,"name":"AOULEF","name_ar":"أولف","name_en":"AOULEF","baladyiats":[{"code":106,"name":"TIT","name_en":"TIT","name_ar":"تيت"},{"code":112,"name":"AOULEF","name_en":"AOULEF","name_ar":"أولف"},{"code":113,"name":"TIMEKTEN","name_en":"TIMEKTEN","name_ar":"تيمقتن"},{"code":119,"name":"AKABLI","name_en":"AKABLI","name_ar":"اقبلي"}]},{"code":115,"name":"FENOUGHIL","name_ar":"فنوغيل","name_en":"FENOUGHIL","baladyiats":[{"code":102,"name":"TAMEST","name_en":"TAMEST","name_ar":"تامست"},{"code":114,"name":"TAMANTIT","name_en":"TAMANTIT","name_ar":"تامنطيط"},{"code":115,"name":"FENOUGHIL","name_en":"FENOUGHIL","name_ar":"فنوغيل"}]},{"code":116,"name":"TINERKOUK","name_ar":"تنركوك","name_en":"TINERKOUK","baladyiats":[{"code":107,"name":"KSAR KADDOUR","name_en":"KSAR KADDOUR","name_ar":"قصر قدور"},{"code":116,"name":"TINERKOUK","name_en":"TINERKOUK","name_ar":"تنركوك"}]},{"code":123,"name":"AOUGROUT","name_ar":"أوقروت","name_en":"AOUGROUT","baladyiats":[{"code":117,"name":"DELDOUL","name_en":"DELDOUL","name_ar":"دلدول"},{"code":120,"name":"METARFA","name_en":"METARFA","name_ar":"المطارفة"},{"code":123,"name":"AOUGROUT","name_en":"AOUGROUT","name_ar":"أوقروت"}]},{"code":125,"name":"BORDJ BADJI MOKHTAR","name_ar":"برج باجي مختار","name_en":"BORDJ BADJI MOKHTAR","baladyiats":[{"code":125,"name":"BORDJ BADJI MOKHTAR","name_en":"BORDJ BADJI MOKHTAR","name_ar":"برج باجي مختار"},{"code":128,"name":"TIMIAOUINE","name_en":"TIMIAOUINE","name_ar":"تيمياوين"}]},{"code":1090,"name":"TIMIMOUN (wilaya déléguée)","name_ar":"تيميمون (ولاية منتدبة)","name_en":"TIMIMOUN (wilaya déléguée)"},{"code":1250,"name":"BORDJ BADJI MOKHTAR (wilaya déléguée)","name_ar":"برج باجي مختار (ولاية منتدبة)","name_en":"BORDJ BADJI MOKHTAR (wilaya déléguée)"}],"adjacentWilayas":[37,8,32,3,47,11]},{"mattricule":2,"name":"Chlef","name_ar":"الشلف","name_en":"Chlef","phoneCodes":[27],"postalCodes":[2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060,2061,2062,2063,2064,2065,2066,2067,2068,2069,2070,2071,2072,2073,2074,2075,2076,2077,2078,2079,2080,2081,2082,2083,2084,2085,2086,2087,2088,2089,2090,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100],"dairats":[{"code":201,"name":"CHLEF","name_ar":"الشلف","name_en":"CHLEF","baladyiats":[{"code":201,"name":"CHLEF","name_en":"CHLEF","name_ar":"الشلف"},{"code":219,"name":"SENDJAS","name_en":"SENDJAS","name_ar":"سنجاس"},{"code":233,"name":"OUM DROU","name_en":"OUM DROU","name_ar":"أم الدروع"}]},{"code":202,"name":"TENES","name_ar":"تنس","name_en":"TENES","baladyiats":[{"code":202,"name":"TENES","name_en":"TENES","name_ar":"تنس"},{"code":211,"name":"SIDI AKKACHA","name_en":"SIDI AKKACHA","name_ar":"سيدي عكاشة"},{"code":225,"name":"SIDI ABDERRAHMANE","name_en":"SIDI ABDERRAHMANE","name_ar":"سيدي عبد الرحمن"}]},{"code":204,"name":"EL KARIMIA","name_ar":"الكريمية","name_en":"EL KARIMIA","baladyiats":[{"code":204,"name":"EL KARIMIA","name_en":"EL KARIMIA","name_ar":"الكريمية"},{"code":209,"name":"HARCHOUN","name_en":"HARCHOUN","name_ar":"حرشون"},{"code":235,"name":"BENI  BOUATTAB","name_en":"BENI  BOUATTAB","name_ar":"بني بوعتاب"}]},{"code":206,"name":"TAOUGRIT","name_ar":"تاوقريت","name_en":"TAOUGRIT","baladyiats":[{"code":206,"name":"TAOUGRIT","name_en":"TAOUGRIT","name_ar":"تاوقريت"},{"code":217,"name":"DAHRA","name_en":"DAHRA","name_ar":"الظهرة"}]},{"code":207,"name":"BENI HAOUA","name_ar":"بني حواء","name_en":"BENI HAOUA","baladyiats":[{"code":207,"name":"BENI HAOUA","name_en":"BENI HAOUA","name_ar":"بني حواء"},{"code":216,"name":"OUED GOUSSINE","name_en":"OUED GOUSSINE","name_ar":"وادي قوسين"},{"code":234,"name":"BREIRA","name_en":"BREIRA","name_ar":"بريرة"}]},{"code":210,"name":"OULED FARES","name_ar":"أولاد فارس","name_en":"OULED FARES","baladyiats":[{"code":210,"name":"OULED FARES","name_en":"OULED FARES","name_ar":"أولاد فارس"},{"code":224,"name":"CHETTIA","name_en":"CHETTIA","name_ar":"الشطية"},{"code":228,"name":"LABIOD MEDJADJA","name_en":"LABIOD MEDJADJA","name_ar":"الأبيض مجاجة"}]},{"code":212,"name":"BOUKADIR","name_ar":"بوقادير","name_en":"BOUKADIR","baladyiats":[{"code":208,"name":"SOBHA","name_en":"SOBHA","name_ar":"الصبحة"},{"code":212,"name":"BOUKADIR","name_en":"BOUKADIR","name_ar":"بوقادير"},{"code":221,"name":"OUED SLY","name_en":"OUED SLY","name_ar":"وادي سلي"}]},{"code":220,"name":"ZEBOUDJA","name_ar":"الزبوجة","name_en":"ZEBOUDJA","baladyiats":[{"code":203,"name":"BENAIRIA","name_en":"BENAIRIA","name_ar":"بنايرية"},{"code":220,"name":"ZEBOUDJA","name_en":"ZEBOUDJA","name_ar":"الزبوجة"},{"code":231,"name":"BOUZEGHAIA","name_en":"BOUZEGHAIA","name_ar":"بوزغاية"}]},{"code":222,"name":"ABOU EL HASSANE","name_ar":"أبو الحسن","name_en":"ABOU EL HASSANE","baladyiats":[{"code":205,"name":"TADJENA","name_en":"TADJENA","name_ar":"تاجنة"},{"code":214,"name":"TALASSA","name_en":"TALASSA","name_ar":"تلعصة"},{"code":222,"name":"ABOU EL HASSANE","name_en":"ABOU EL HASSANE","name_ar":"أبو الحسن"}]},{"code":223,"name":"EL MARSA","name_ar":"المرسى","name_en":"EL MARSA","baladyiats":[{"code":223,"name":"EL MARSA","name_en":"EL MARSA","name_ar":"المرسى"},{"code":226,"name":"MOUSSADEK","name_en":"MOUSSADEK","name_ar":"مصدق"}]},{"code":229,"name":"OUED FODDA","name_ar":"وادي الفضة","name_en":"OUED FODDA","baladyiats":[{"code":213,"name":"BENI RACHED","name_en":"BENI RACHED","name_ar":"بني راشد"},{"code":218,"name":"OULED ABBES","name_en":"OULED ABBES","name_ar":"أولاد عباس"},{"code":229,"name":"OUED FODDA","name_en":"OUED FODDA","name_ar":"وادي الفضة"}]},{"code":230,"name":"OULED BEN ABDELKADER","name_ar":"أولاد بن عبد القادر","name_en":"OULED BEN ABDELKADER","baladyiats":[{"code":227,"name":"EL HADJADJ","name_en":"EL HADJADJ","name_ar":"الحجاج"},{"code":230,"name":"OULED BEN ABDELKADER","name_en":"OULED BEN ABDELKADER","name_ar":"أولاد بن عبد القادر"}]},{"code":232,"name":"AIN MERANE","name_ar":"عين مران","name_en":"AIN MERANE","baladyiats":[{"code":215,"name":"HERENFA","name_en":"HERENFA","name_ar":"الهرانفة"},{"code":232,"name":"AIN MERANE","name_en":"AIN MERANE","name_ar":"عين مران"}]}],"adjacentWilayas":[27,48,7,38,44,42]},{"mattricule":3,"name":"Laghouat","name_ar":"الأغواط","name_en":"Laghouat","phoneCodes":[29],"postalCodes":[3000,3001,3002,3003,3004,3005,3006,3007,3008,3009,3010,3011,3012,3013,3014,3015,3016,3017,3018,3019,3020,3021,3022,3023,3024,3025,3026,3027,3028,3030,3031,3032,3033,3034,3035,3036,3037,3038,3040,3041,3042,3043,3044,3046,3047,3048,3049,3050,3051,3052,3053,3054],"dairats":[{"code":301,"name":"LAGHOUAT","name_ar":"الأغواط","name_en":"LAGHOUAT","baladyiats":[{"code":301,"name":"LAGHOUAT","name_en":"LAGHOUAT","name_ar":"الأغواط"}]},{"code":302,"name":"KSAR EL HIRANE","name_ar":"قصر الحيران","name_en":"KSAR EL HIRANE","baladyiats":[{"code":302,"name":"KSAR EL HIRANE","name_en":"KSAR EL HIRANE","name_ar":"قصر الحيران"},{"code":303,"name":"BENACER BENCHOHRA","name_en":"BENACER BENCHOHRA","name_ar":"بن ناصر بن شهرة"}]},{"code":304,"name":"SIDI MAKHLOUF","name_ar":"سيدي مخلوف","name_en":"SIDI MAKHLOUF","baladyiats":[{"code":304,"name":"SIDI MAKHLOUF","name_en":"SIDI MAKHLOUF","name_ar":"سيدي مخلوف"},{"code":320,"name":"EL ASSAFIA","name_en":"EL ASSAFIA","name_ar":"العسافية"}]},{"code":306,"name":"HASSI R'MEL","name_ar":"حاسي الرمل","name_en":"HASSI R'MEL","baladyiats":[{"code":305,"name":"HASSI DELAA","name_en":"HASSI DELAA","name_ar":"حاسي الدلاعة"},{"code":306,"name":"HASSI R'MEL","name_en":"HASSI R'MEL","name_ar":"حاسي الرمل"}]},{"code":307,"name":"AIN MADHI","name_ar":"عين ماضي","name_en":"AIN MADHI","baladyiats":[{"code":307,"name":"AIN MADHI","name_en":"AIN MADHI","name_ar":"عين ماضي"},{"code":308,"name":"TADJEMOUT","name_en":"TADJEMOUT","name_ar":"تاجموت"},{"code":309,"name":"KHENEG","name_en":"KHENEG","name_ar":"الخنق"},{"code":318,"name":"TADJROUN
